name: Pulumi
on:
  - workflow_dispatch
jobs:
  preview:
    name: Preview
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: home # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
