name: Pulumi
on:
  - workflow_dispatch
jobs:
  preview:
    name: Preview
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: rasp-pi # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: rasp-pi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
